use_frameworks!

platform :ios, '9.0'

target 'NetworkGenericiOS_Example' do
  pod 'NetworkGenericiOS', :path => '../'

  target 'NetworkGenericiOS_Tests' do
    inherit! :search_paths

    
  end
end
